#!/bin/sh
if [[ "$NODE_ENV" != "production" ]]; then
    . "$(dirname "$0")/_/husky.sh"

    echo "\n 🚧 Dependencies are being installed, please wait for a while. ⏳\n"

    npm install

    echo "\nCongratulations, you are good to go! ⚡⚡⚡\n"
fi
